apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: common-annotations
annotations:
  app.kubernetes.io/name: qliksense
  app.kubernetes.io/instance: $(PREFIX)
  app.kubernetes.io/version: 1.50.3 
  app.kubernetes.io/managed-by: qliksense-operator
fieldSpecs:
  - path: metadata/annotations
    create: true

