apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dcaas
resources:
- helmchart.yaml
- configs
- secrets
transformers:
- ../../../../../transformers
- ../secrets
- ../configs
- redisvalues.yaml
