apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: keys
    chart: keys-1.5.8
    heritage: Helm
    release: keys
  name: keys
spec:
  ports:
  - name: keys
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keys
    release: keys
  type: ClusterIP
---
