apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: collections-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: collections-configs
    data:
      pdsUri: "http://$(PREFIX)-collections-policy-decisions:5080"
      natsUri: "nats://$(PREFIX)-collections-messaging-nats-client:4222"
      keysUri: "http://$(PREFIX)-collections-keys:8080/v1/keys/qlik.api.internal"
      tokenAuthUri: "http://$(PREFIX)-collections-edge-auth:8080/v1"
      natsStreamingClusterId: "$(PREFIX)-collections-messaging-nats-streaming-cluster"
