apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: web-security
resources:
  - resources
generators:
  - generators
transformers:
  - secrets
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/release
  - ../../vars
  - ../../transformers/msgprefix
  - ../../transformers/prefix
  - ../../transformers/namespace

images:
  - name: qlik-docker-qsefe.bintray.io/web-security
    newName: $(IMAGE_REGISTRY)/web-security
