apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keys
resources:
  - resources
transformers:
  - super-configs
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/release
  - ../../vars
  - ../../transformers/msgprefix
  - ../../transformers/prefix
  - ../../transformers/namespace
images:
  - name: qlik-docker-qsefe.bintray.io/keys
    newName: $(IMAGE_REGISTRY)/keys
