apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: elastic-infra-secrets-crt
target:
  kind: Secret
  name: elastic-infra-elastic-infra-tls-secret
path: data/tls.crt
search: (?s).*
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: Secret
    mame: elastic-infra-secrets
  fieldref:
    fieldpath: data.tlsCrt