apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: data-connector-qwc
resources:
  - ../patches
  - ../secrets
  - ../configs
  - ../transformers
  - ../../dcaas/generators/secrets
  - ../dcaas-generators-configs
  - ../../qliksense/generators/secrets
  - ../../qliksense/generators/configs
  - ../../../../../.operator/patches
  - ../../../../../configuration/patches
  - ../../../transformers/base
  - ../../../transformers/msgprefix