apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: chronos
generators:
  - generators
transformers:
  - patches
  - secrets
  - configs
  - transformers
  - ../qliksense/generators/configs
  - ../qliksense/generators/secrets
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/base
  - ../../transformers/msgprefix
images:
  - name: qlik-docker-qsefe.bintray.io/chronos
    newName: $(IMAGE_REGISTRY)/chronos
  - name: qlik-docker-qsefe.bintray.io/leader-elector
    newName: $(IMAGE_REGISTRY)/leader-elector
