apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: qix-sessions
    chart: qix-sessions-5.6.7
    heritage: Helm
    release: qix-sessions
  name: qix-sessions
  namespace: $(NAMESPACE)
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - pods
  - configmaps
  - events
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - qixmanager.qlik.com
  resources:
  - engines
  - engines/finalizers
  verbs:
  - '*'
---
