apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - searchReplaceStorageClassName.yaml
  - ../../../resources/qliksense/generators/configs
transformers:
  - ../../../../../.operator/configs
  - ../../../../../configuration/configs
  - searchReplaceStorageClassName2.yaml