apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: precedentsUriDeployment
  labels:
    key: precedentsUri
    kind: Deployment
enabled: true
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: PRECEDENTS_URI
              valueFrom:
                configMapKeyRef:
                  key: precedentsUri
                  name: configs