apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: messaging
generators:
  - generators
transformers:
- patches
- configs
- transformers
- ../qliksense/generators/secrets
- ../qliksense/generators/configs
- ../../../../.operator/patches
- ../../../../configuration/patches
- last-mile-transformers
- ../../transformers/base
- ../../transformers/msgprefix
images:
- name: qlik-docker-qsefe.bintray.io/nats-streaming
  newName: $(IMAGE_REGISTRY)/nats-streaming
- name: qlik-docker-qsefe.bintray.io/prometheus-nats-exporter
  newName: $(IMAGE_REGISTRY)/prometheus-nats-exporter
- name:  qlik-docker-qsefe.bintray.io/qnatsd
  newName: $(IMAGE_REGISTRY)/qnatsd
