apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# commonLabels:
#   app: engine
resources:
  - resources
generators:
  - generators
transformers:
  - all-transformers
images:
- name: qlik-docker-qsefe.bintray.io/engine
  newName: $(IMAGE_REGISTRY)/engine
- name: qlik-docker-qsefe.bintray.io/engine-qv
  newName: $(IMAGE_REGISTRY)/engine-qv
# configurations:
#   - ../../namereference.yaml
