apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: encryption
resources:
  - resources
generators:
  - generators
transformers:
  - configs
  - secrets
  - transformers 
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/release
  - ../../vars
  - ../../transformers/msgprefix
  - ../../transformers/prefix
  - ../../transformers/namespace
images:
- name: qlik-docker-qsefe.bintray.io/encryption
  newName: $(IMAGE_REGISTRY)/encryption
