apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sharing-pruning
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: PRUNE_ONLY
              value: "true"
            - name: ENVIRONMENT
              value: k8s
            - name: NATS_ENABLED
              value: "false"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: mongodb-uri
                  name: sharing-mongoconfig
            image: qlik-docker-qsefe.bintray.io/sharing:3.0.52
            imagePullPolicy: IfNotPresent
            name: main
          imagePullSecrets:
          - name: artifactory-docker-secret
          restartPolicy: Never
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1
---
