apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: hub-configs 
    fieldref:
      fieldpath: metadata.namespace
  - name: PREFIX 
    objref:
      apiVersion: v1
      kind: ConfigMap 
      name: hub-configs 
    fieldref:
      fieldpath: metadata.labels.release
  - name: INGRESS_CLASS 
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: hub-configs
    fieldref:
      fieldpath: data.ingressClass
configurations:
  - varreference.yaml
resources:
  - ../../resources/hub
