apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: generic-links
generators:
  - generators
transformers:
  - patches
  - secrets
  - configs
  - transformers
  - ../qliksense/generators/secrets 
  - ../qliksense/generators/configs
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/base
  - ../../transformers/msgprefix
images:
  - name: qlik-docker-qsefe.bintray.io/generic-links
    newName: $(IMAGE_REGISTRY)/generic-links
