apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: licenses
    chart: licenses-1.19.0
    heritage: Helm
    release: licenses
  name: licenses
  namespace: $(NAMESPACE)
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - update
  - create
---
