apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: elastic-infra
resources:
  - resources
generators:
  - generators
transformers:
  - secrets
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/release
  - vars
  - ../../transformers/msgprefix
  - ../../transformers/prefix
  - ../../transformers/namespace
images:
  - name: qlik-docker-qsefe.bintray.io/nginx-ingress-controller
    newName: $(IMAGE_REGISTRY)/nginx-ingress-controller
configurations:
  - ../../namereference.yaml
