apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: elastic-infra
generators:
  - generators
transformers:
  - patches
  - secrets
  - transformers
  - ../qliksense/generators/secrets 
  - ../qliksense/generators/configs  
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/base
  - ../../transformers/msgprefix

images:
- name: qlik-docker-qsefe.bintray.io/nginx-ingress-controller
  newName: $(IMAGE_REGISTRY)/nginx-ingress-controller
configurations:
  - ../../namereference.yaml