apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hub 
generators:
  - generators
transformers:
  - patches
  - transformers
  - secrets
  - configs
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/base
  - ../../transformers/msgprefix
images:
  - name: qlik-docker-qsefe.bintray.io/hub
    newName: $(IMAGE_REGISTRY)/hub
