apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qix-datafiles
resources:
  - ../../../transformers
transformers:
  - ../../../../../.operator/transformers
  - ../../../../../configuration/transformers
#Disable all transformers except these
patches:
  - target:
      labelSelector: >-
        key notin (
          imageRegistry,
          ingressClass,
          natsUri,
          natsStreamingClusterId,
          tokenAuthUri,
          keysUri,
          pdsUri,
          mongodbUri,
          caCertificates,
          usersUri,
          spacesUri,
          featureFlagsUri,
          encryptionUri,
          tokenAuthPrivateKey,
          tokenAuthPrivateKeyId,
          storageClassName
        )
    patch: |-
      - op: replace
        path: /enabled
        value: false
      - op: replace
        path: /default
        value: true
