apiVersion: v1
data:
  gnatsd.conf: |-
    listen: 0.0.0.0:4222
    http: 0.0.0.0:8222
    client_advertise: messaging-nats-client:4222

    # Authorization for client connections
    authorization {
      timeout:  1
      users: [
        {
          user: "nats_client",
          password: "T0pS3cr3t",
        }
      ]
    }

    # Logging options
    debug: false
    trace: false
    logtime: false

    # Pid file
    pid_file: "/tmp/gnatsd.pid"

    # Some system overides


    # Clustering definition
    cluster {
      listen: 0.0.0.0:6222

      no_advertise: false

      # Authorization for cluster connections

      # Routes are actively solicited and connected to from this server.
      # Other servers can connect to us if they supply the correct credentials
      # in their routes definitions from above
      routes = [
        nats://messaging-nats-cluster:6222
      ]
    }
  users.json: '[{"stanPermissions":{"subscribe":["system-events.odag.request","system-events.engine.app","system-events.user-session","system-events.spaces","system-events.licenses","system-events.generic-links","system-events.api-keys","system-events.user-identity","system-events.web-security","system-events.tenants"]},"user":"audit"},{"stanPermissions":{"publish":["chronos-worker.>"]},"user":"chronos-worker"},{"stanPermissions":{"subscribe":["system-events.>"]},"user":"data-engineering-exporter"},{"stanPermissions":{"publish":["system-events.user-session","system-events.user-identity"],"subscribe":["system-events.users","system-events.user-session","system-events.identity-providers","private.idp-sync"]},"user":"edge-auth"},{"stanPermissions":{"publish":["com.qlik.app","com.qlik.engine.session","com.qlik.engine.system","system-events.engine.app","system-events.engine.session","system-events.engine.system"]},"user":"engine"},{"stanPermissions":{"publish":["private.idp-sync","system-events.identity-providers"]},"user":"identity-providers"},{"stanPermissions":{"publish":["system-events.invite"],"subscribe":["system-events.users"]},"user":"invite"},{"stanPermissions":{"subscribe":["system-events.engine.app"]},"user":"nl-parser"},{"stanPermissions":{"publish":["system-events.odag.request","odag.>"],"subscribe":["odag.>","system-events.engine.app","system-events.reloadResults"]},"user":"odag"},{"stanPermissions":{"publish":["reload","system-events.reloadResults"],"subscribe":["reload"]},"user":"qix-data-reload"},{"stanPermissions":{"publish":["system-events.resource-library"]},"user":"resource-library"},{"stanPermissions":{"publish":["system-events.tenants","system-events.web-integrations"]},"user":"tenants"},{"stanPermissions":{"publish":["system-events.users"]},"user":"users"},{"stanPermissions":{"publish":["system-events.api-keys"]},"user":"api-keys"},{"stanPermissions":{"publish":["system-events.items"],"subscribe":["system-events.engine.app"]},"user":"collections"},{"stanPermissions":{"publish":["system-events.licenses"],"subscribe":["system-events.licenses"]},"user":"licenses"},{"stanPermissions":{"publish":["system-events.spaces"],"subscribe":["system-events.tenants"]},"user":"spaces"},{"stanPermissions":{"subscribe":["system-events.engine.app"]},"user":"precedents"},{"stanPermissions":{"publish":["system-events.notification-request"],"subscribe":["system-events.engine.app","system-events.spaces","system-events.web-notifications"]},"user":"eventing"},{"stanPermissions":{"subscribe":["system-events.engine.app","system-events.engine.session","system-events.engine.system","system-events.reloadResults"]},"user":"qix-sessions"},{"stanPermissions":{"subscribe":["system-events.engine.app","system-events.spaces"]},"user":"qix-datafiles"},{"stanPermissions":{"publish":["system-events.notification-request","system-events.sharing"],"subscribe":["system-events.engine.app"]},"user":"sharing"},{"stanPermissions":{"subscribe":["system-events.engine.app"]},"user":"subscriptions"},{"stanPermissions":{"publish":["system-events.transport-request"],"subscribe":["system-events.notification-request"]},"user":"notification-prep"},{"stanPermissions":{"publish":["system-events.web-notifications"],"subscribe":["system-events.transport-request"]},"user":"web-notifications"},{"stanPermissions":{"publish":["system-events.generic-links"]},"user":"generic-links"},{"stanPermissions":{"subscribe":["system-events.spaces"]},"user":"data-connections"},{"stanPermissions":{"publish":["system-events.transport-response"],"subscribe":["system-events.transport-request"]},"user":"transport"},{"stanPermissions":{"publish":["system-events.web-security"]},"user":"web-security"},{"stanPermissions":{"subscribe":["system-events.engine.app"]},"user":"reload-tasks"},{"stanPermissions":{"publish":["reporting.>"]},"user":"reporting"},{"stanPermissions":{"publish":["nl-app-search.>"],"subscribe":["system-events.engine.app","system-events.reloadResults","nl-app-search.>"]},"user":"nl-app-search"},{"stanPermissions":{"subscribe":["system-events.users"]},"user":"user-info"}]'
kind: ConfigMap
metadata:
  labels:
    app: nats
    chart: nats-2.4.1
    heritage: Helm
    release: messaging
  name: messaging-nats
---
