apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
    chart: nats-2.4.1
    heritage: Helm
    release: messaging
  name: messaging-nats-client
spec:
  ports:
  - name: client
    port: 4222
    targetPort: client
  selector:
    app: nats
    release: messaging
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
    chart: nats-2.4.1
    heritage: Helm
    release: messaging
  name: messaging-nats-cluster
spec:
  ports:
  - name: cluster
    port: 6222
    targetPort: cluster
  selector:
    app: nats
    release: messaging
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
    chart: nats-2.4.1
    heritage: Helm
    release: messaging
  name: messaging-nats-headless
spec:
  clusterIP: None
  ports:
  - name: client
    port: 4222
    targetPort: client
  - name: cluster
    port: 6222
    targetPort: cluster
  selector:
    app: nats
    release: messaging
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "7777"
    prometheus.io/scrape: "true"
  labels:
    app: nats
    chart: nats-2.4.1
    heritage: Helm
    release: messaging
  name: messaging-nats-monitoring
spec:
  ports:
  - name: monitoring
    port: 8222
    targetPort: monitoring
  selector:
    app: nats
    release: messaging
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "7777"
    prometheus.io/scrape: "true"
  labels:
    app: nats-streaming
    chart: nats-streaming-0.4.0
    heritage: Helm
    release: messaging
  name: messaging-nats-streaming-monitoring
spec:
  ports:
  - name: monitoring
    port: 8222
    targetPort: monitoring
  selector:
    app: nats-streaming
    release: messaging
  type: ClusterIP
---
