apiVersion: v1
data:
  mongodbUri: IA==
  tokenAuthPrivateKey: IA==
  tokenAuthPrivateKeyId: IA==
kind: Secret
metadata:
  labels:
    app: audit
    chart: audit-3.3.4
    heritage: Helm
    release: audit
  name: audit-secrets
  namespace: $(NAMESPACE)
type: Opaque
---
