apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:

  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: messaging-configs 
    fieldref:
      fieldpath: metadata.namespace
  - name: PREFIX 
    objref:
      apiVersion: v1
      kind: ConfigMap 
      name: messaging-configs 
    fieldref:
      fieldpath: metadata.labels.release
  - name: IMAGE_REGISTRY
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: messaging-configs
    fieldref:
      fieldpath: data.imageRegistry
configurations:
  - ../../varreference.yaml
resources:
  - ../../resources/messaging
