apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: storageClassName
  labels:
    key: storageClassName
enabled: true
patches:
- target:
    kind: PersistentVolumeClaim
  patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: component
    spec:
      storageClassName: $(STORAGE_CLASS_NAME)
- target:
    kind: SearchReplace
    labelSelector: key=ingressAuthUrl
  patch: |-
    apiVersion: qlik.com/v1
    kind: SearchReplace
    metadata:
      name: storageClassName
    replaceWithObjRef: null
    replace: $(STORAGE_CLASS_NAME)