apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: edge-auth
generators:
  - generators
transformers:
  - patches
  - secrets
  - configs
  - transformers
  - ../qliksense/generators/secrets 
  - ../qliksense/generators/configs  
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/base
  - ../../transformers/msgprefix
images:
- name: qlik-docker-qsefe.bintray.io/edge-auth
  newName: $(IMAGE_REGISTRY)/edge-auth
- name: qlik/simple-oidc-provider
  newName: $(IMAGE_REGISTRY)/simple-oidc-provider