apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: management-console
generators:
  - generators
transformers:
  - patches
  # - secrets
  # - configs
  - transformers
  #- ../qliksense/generators/secrets 
  - ../qliksense/generators/configs
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/base
  - ../../transformers/msgprefix
images:
  - name: qlik-docker-qsefe.bintray.io/management-console
    newName: $(IMAGE_REGISTRY)/management-console
