apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qix-data-connection
resources:
  - ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin ( 
        ingressClass,
        qixDataFilesUri,
        tokenAuthUri,
        keysUri,
        encryptionUri,
        spacesUri, 
        mongodbUri,
        caCertificates,
        tokenAuthPrivateKey,
        tokenAuthPrivateKeyId
      )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true