apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component- imageRegistry-replace2
target:
  kind: SearchReplace
path: replace
search: \$\(IMAGE_REGISTRY\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
  fieldref:
    fieldpath: data.imageRegistry
