apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qliksense
resources:
  - resources
generators:
  - generators
transformers:
  - secrets
  - configs
  - transformers
  - ../../transformers/release
  - vars
  - ../../transformers/prefix
  - ../../transformers/namespace
