apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qliksense
resources:
  - resources
generators:
  - generators
resources:
  - resources
transformers:
  - secrets
  - configs
  - ../../transformers/base
  - transformers