apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: chronos-worker-component-secrets
enabled: true
patches:
- target:
    kind: SuperSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: chronos-worker-secrets
    stringData:
      tokenAuthPrivateKeyId: (( (ds "data").kid ))
      tokenAuthPrivateKey: |
        ((- "\n"))(( (ds "data").private_key | indent 8 ))
      redisPassword: "NGkUp0VDJtc3xiyC"
