apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- encryptionUri
- featureFlagsUri
- groupsUri
- identityProvidersUri
- identityProvidersExtUri
- idpConfigs
- imageRegistry
- ingressAuthUrl
- ingressClass
- keysUri
- mongodbUri
- natsStreamingClusterId
- natsUri
- pdsUri
- redisPassword
- redisUri
- tenantsUri
- spacesUri
- tokenAuthUri
- usersUri
- qixSessionsUri
- qixDataFilesUri
- precedentsUri
- licensesUri
- quotasUri
- temporaryContentsUri
- acceptEULA
- engineUri
- redisUriWithPort
- dcaasUri
- qixDataConnectionUri
- geoOperationsUri
- storageClassName
- reloadTasksUri
- qixDataReloadUri
- chronosUri
- reportingUri
- collectionsUri
- nlParserUri
- dataPrepUri
- insightsUri
- keysUriTemp
- tokenAuthUriTemp
- licensesUriTemp
- caCertificates
- redisHost
- apiKeysUri
- usersUriTemp
- subscriptionsUri
- dataConnectionsUri
