apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: data-connector-odbc
resources:
- ../../../transformers
- ../../dcaas/transformers/redisUri
- ../../dcaas/transformers/redisPassword
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
patches:
- target:
    labelSelector: >-
      key notin (
        imageRegistry,
        dcaasRedisUri,
        dcaasRedisPassword
      )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: false