apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odag
resources:
  - resources
generators:
  - generators
transformers:
  - secrets
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/release
  - vars
  - ../../transformers/msgprefix
  - ../../transformers/prefix
  - ../../transformers/namespace
images:
- name: qlik-docker-qsefe.bintray.io/odag
  newName: $(IMAGE_REGISTRY)/odag
- name: qlik-docker-qsefe.bintray.io/leader-elector
  newName: $(IMAGE_REGISTRY)/leader-elector
