apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keys
resources:
  - ../patches
  - ../super-configs
  - ../configs
  - ../../qliksense/generators/configs
  - ../../../../../.operator/patches
  - ../../../../../configuration/patches
  - ../../../transformers/base
  - ../../../transformers/msgprefix