apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-storageClass
target:
  kind: PersistentVolumeClaim
path: /
search: \$\(STORAGE_CLASS_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.storageClassName
