apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


vars:
  - name: PREFIX 
    objref:
      apiVersion: v1
      kind: ConfigMap 
      name: keys-configs 
    fieldref:
      fieldpath: metadata.labels.release
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: keys-configs 
    fieldref:
      fieldpath: metadata.namespace
  - name: IMAGE_REGISTRY
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: keys-configs
    fieldref:
      fieldpath: data.imageRegistry

configurations:
  - ../../varreference.yaml
resources:
  - ../../resources/keys