apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generators
transformers:
  - patches
  - secrets
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../../base/transformers/release
  - ../../../base/vars
  - ../../../base/transformers/prefix
  - ../../../base/transformers/namespace
images:
  - name: qlik-docker-qsefe.bintray.io/redis
    newName: $(IMAGE_REGISTRY)/redis
