apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- statefulset.yaml
- ingress.yaml
- engine.yaml
- persistentvolumeclaim.yaml
