apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mongodb
generators:
- generators
transformers:
- patches
- ../../../base/transformers/release
- ../../../base/vars
- ../../../base/transformers/prefix
- ../../../base/transformers/namespace
images:
  - name: docker.io/bitnami/mongodb
    newName: $(IMAGE_REGISTRY)/mongodb
