apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: tenants
resources:
  - ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin (
        imageRegistry,
        ingressClass,
        ingressAuthUrl,
        featureFlagsUri,
        natsStreamingClusterId,
        natsUri,
        keysUriTemp,
        mongodbUri,
        caCertificates,
        usersUriTemp,
        licensesUriTemp,
        tokenAuthUriTemp,
        tokenAuthPrivateKey,
        tokenAuthPrivateKeyId,
        natsUri,
        natsStreamingClusterId
        )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
