apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: audit
resources:
  - resources
transformers:
  - secrets
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../transformers/release
  - ../../vars
  - ../../transformers/msgprefix
  - ../../transformers/prefix

images:
  - name: qlik-docker-qsefe.bintray.io/audit
    newName: $(IMAGE_REGISTRY)/audit